### PR TITLE
synchornize database when a TaskRequest is failed

### LINKED ISSUE #203: Manually update task status when task is cancelled or an Android exception occurs during its execution
## Observed behavior

When a task is cancelled by the Android system (interrupted) or perhaps if it fails with an exception on the Android side, the task could get into a state where it would have to wait for the next reconciliation to be properly handled within Kolibri. This may cause significant delays and the user may not realize why.

## Errors and logs

```
2024-01-29 20:55:48.388  9506-9597  Kolibri.Fo...oundWorker org.learningequality.Kolibri         D  Stopping foreground remote task aa73f1bc-8393-4675-8070-d51e234cfdf6
2024-01-29 20:55:48.388  9506-9506  WM-Processor            org.learningequality.Kolibri         D  Processor aa73f1bc-8393-4675-8070-d51e234cfdf6 executed; reschedule = true
2024-01-29 20:55:48.388  9506-9506  WM-SystemJobService     org.learningequality.Kolibri         D  aa73f1bc-8393-4675-8070-d51e234cfdf6 executed on JobScheduler
2024-01-29 20:55:48.390  9506-9597  WM-Processor            org.learningequality.Kolibri         D  WorkerWrapper interrupted for aa73f1bc-8393-4675-8070-d51e234cfdf6
2024-01-29 20:55:48.391  9506-9597  WM-StopWorkRunnable     org.learningequality.Kolibri         D  StopWorkRunnable for aa73f1bc-8393-4675-8070-d51e234cfdf6; Processor.stopWork = true
2024-01-29 20:55:48.393  9506-9597  WM-WorkerWrapper        org.learningequality.Kolibri         I  Work [ id=aa73f1bc-8393-4675-8070-d51e234cfdf6, tags={ kolibri_job_type:kolibri.core.auth.tasks.soud_sync_processing, kolibri_job_long_running, kolibri_task_id:50, org.learningequality.Kolibri.ForegroundWorker } ] was cancelled
                                                                                                    java.util.concurrent.CancellationException: Task was cancelled.
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1183)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:513)
                                                                                                    	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
                                                                                                    	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
                                                                                                    	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:784)
2024-01-29 20:55:48.393  9506-9597  WM-WorkerWrapper        org.learningequality.Kolibri         D  Work interrupted for Work [ id=aa73f1bc-8393-4675-8070-d51e234cfdf6, tags={ kolibri_job_type:kolibri.core.auth.tasks.soud_sync_processing, kolibri_job_long_running, kolibri_task_id:50, org.learningequality.Kolibri.ForegroundWorker } ]
```

## Expected behavior

Since we [already have code](https://github.com/learningequality/kolibri-installer-android/blob/develop/python-for-android/dists/kolibri/src/main/java/org/learningequality/Kolibri/task/Reconciler.java) that implements reconciliation by writing directly to the `job_storage.sqlite3` database, we can reuse that to make additional defensive handling that more swiftly reconciles tasks with Kolibri under specific circumstances:

1) When the worker's `onStopped` method is called: we're allowed to do _synchronous_ operations in this method ([ref](https://github.com/learningequality/kolibri-installer-android/blob/develop/python-for-android/dists/kolibri/src/main/java/org/learningequality/Kolibri/BackgroundWorker.java#L43), [ref](https://github.com/learningequality/kolibri-installer-android/blob/develop/python-for-android/dists/kolibri/src/main/java/org/learningequality/Kolibri/ForegroundWorker.java))
2) When the result from processing the task encounters an exception: this generally doesn't happen if the task fails within python, so this catches the Android side of it ([ref](https://github.com/learningequality/kolibri-installer-android/blob/develop/python-for-android/dists/kolibri/src/main/java/org/kivy/android/PythonWorker.java#L68))

## User-facing consequences

Longer delays during task processing when edge cases occur

## Context

Kolibri 0.16.0 on Android

### PR DESCRIPTION
**Pull request by ozer550**
closes #203

- Updates task in the database to be marked as failed when its canceled from the Android side!

### CODE REVIEW

File: python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java [hunk 1]
```diff
@@ -25,10 +27,13 @@ abstract public class Worker extends androidx.work.Worker implements Notifier {
     private int lastProgressUpdateHash;
     private Notification lastNotification;
 
+    private final JobStorage db;
+
     public Worker(
             @NonNull Context context, @NonNull WorkerParameters workerParams
     ) {
         super(context, workerParams);
+        this.db = JobStorage.readwrite(context);
```
Comment (bjester) [inline python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java]: The `JobStorage` class inherits `Database` which in turn implements the `AutoCloseable` interface, which infers that the instance _must_ be closed when it is no longer needed. The `AutoCloseable` interface works in conjunction with a [try-with-resources statement](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html). You may use the `getApplicationContext` method to instantiate it within a try-with-resources block, outside of the constructor.

I think it's worth having only the `Worker` handle the task update, and if necessary, update the `PythonWorker` to return the necessary information that allows `Worker` to determine if and when it needs to update the task status. Then that way we only have one place, within the worker code, updating the task status. When we move to Chaquopy, we'll replace `PythonWorker`, so if it has logic that isn't distinct to python-for-android, it should live in `Worker`.

File: python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java [hunk 2]
```diff
@@ -64,16 +69,29 @@ public void update(TaskWorkerImpl.Message message) {
...
-        return r;
+      return r;
     }
 
     @Override
     public void onStopped() {
         Log.d(TAG, "Stopping background remote task " + getId());
+        // Here we need to update the task in the database to be marked as failed
+        if(updateTaskStatus(getId().toString())==0){
+            Log.e(TAG, "Failed to update TaskStatus for remote Task" + getId());
```
Comment (bjester) [inline python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java]: space after the string, otherwise the ID will conjoin with the message.

File: python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java [hunk 3]
```diff
@@ -64,16 +69,29 @@ public void update(TaskWorkerImpl.Message message) {
...
+        };
         hideNotification();
         super.onStopped();
     }
 
+    protected int updateTaskStatus(String id) {
+        Log.d(TAG, "Updating Task Status for job " + id);
+        UpdateQuery q = new UpdateQuery(JobStorage.Jobs.TABLE_NAME)
+                .where(JobStorage.Jobs.worker_extra, id)
+                .set(JobStorage.Jobs.state, JobStorage.Jobs.State.FAILED.toString());
```
Comment (bjester) [inline python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java]: Coming from `onStopped`, we should set the task status to cancelled.

File: python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java [hunk 4]
```diff
@@ -64,16 +69,29 @@ public void update(TaskWorkerImpl.Message message) {
...
+            Log.e(TAG, "Failed to update TaskStatus for remote Task" + getId());
+        };
         hideNotification();
         super.onStopped();
     }
 
+    protected int updateTaskStatus(String id) {
+        Log.d(TAG, "Updating Task Status for job " + id);
+        UpdateQuery q = new UpdateQuery(JobStorage.Jobs.TABLE_NAME)
+                .where(JobStorage.Jobs.worker_extra, id)
```
Comment (bjester) [inline python-for-android/dists/kolibri/src/main/java/org/learningequality/task/Worker.java]: Since the python side is responsible for setting `worker_extra` to the Android Work Manager ID, and that 'python side' is invoked via `PythonWorker`, we should probably just filter on the task ID, which is available via `getArgument()` as seen in `doWork` above. If the code never got as far as executing the python-side, then `worker_extra` wouldn't match.

**Review by bjester — DISMISSED** [review]
All of the necessary bits and pieces are here, but some restructuring is needed. Also, if you would please make sure your code is formatted in the same conventions as the existing code, e.g. spaces after `if` and between `if` conditions and operators.

**Review by bjester — COMMENTED** [review]
Looks perfect, just some minor formatting updates needed. Mostly adding whitespace, and perhaps removing some extraneous semicolons

**Review by bjester — APPROVED** [review]
Nice work! QA so far seems good to go, but lets wait to merge

**Comment by pcenov** [comment]
Both me and @radinamatic didn't observe any new issues while syncing the devices - manual QA checks out!
